<a href="https://colab.research.google.com/github/YM1587/care-me/blob/main/patient_triage_management.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ilkeryildiz/emergency-service-triage-application")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'emergency-service-triage-application' dataset.
Path to dataset files: /kaggle/input/emergency-service-triage-application

In [ ]:
import os
import pandas as pd

# List contents of the downloaded directory
print("Files in dataset directory:")
for dirname, _, filenames in os.walk(path):
    for filename in filenames:
        print(os.path.join(dirname, filename))

Files in dataset directory:
/kaggle/input/emergency-service-triage-application/data.csv

In [ ]:
data_file_path = os.path.join(path, 'data.csv')
df = pd.read_csv(data_file_path, encoding='latin1', sep=';', decimal=',')

display(df.head())

,Group,Sex,Age,Patients number per hour,Arrival mode,Injury,Chief_complain,Mental,Pain,NRS_pain,...,BT,Saturation,KTAS_RN,Diagnosis in ED,Disposition,KTAS_expert,Error_group,Length of stay_min,KTAS duration_min,mistriage
0,2,2,71,3,3,2,right ocular pain,1,1,2,...,36.6,100,2,Corneal abrasion,1,4,2,86,5.00,1
1,1,1,56,12,3,2,right forearm burn,1,1,2,...,36.5,NaN,4,"Burn of hand, firts degree dorsum",1,5,4,64,3.95,1
2,2,1,68,8,2,2,"arm pain, Lt",1,1,2,...,36.6,98,4,"Fracture of surgical neck of humerus, closed",2,5,4,862,1.00,1
3,1,2,71,8,1,1,ascites tapping,1,1,3,...,36.5,NaN,4,Alcoholic liver cirrhosis with ascites,1,5,6,108,9.83,1
4,1,2,58,4,3,1,"distension, abd",1,1,3,...,36.5,NaN,4,Ascites,1,5,8,109,6.60,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  1267 non-null   object
 10  SBP                       1267 non-null   object
 11  DBP                       1267 non-null   object
 12  HR                        1267 non-null   object
 13  RR                        1267 non-null   object
 14  BT                        1267 non-null   object
 15  Saturation                579 non-null    object
 16  KTAS_RN                   1267 non-null   int64
 17  Diagnosis in ED           1265 non-null   object
 18  Disposition               1267 non-null   int64
 19  KTAS_expert               1267 non-null   int64
 20  Error_group               1267 non-null   int64
 21  Length of stay_min        1267 non-null   int64
 22  KTAS duration_min         1267 non-null   float64
 23  mistriage                 1267 non-null   int64
dtypes: float64(1), int64(14), object(9)
memory usage: 237.7+ KB

In [ ]:
df.isnull().sum()

Group                         0
Sex                           0
Age                           0
Patients number per hour      0
Arrival mode                  0
Injury                        0
Chief_complain                0
Mental                        0
Pain                          0
NRS_pain                      0
SBP                           0
DBP                           0
HR                            0
RR                            0
BT                            0
Saturation                  688
KTAS_RN                       0
Diagnosis in ED               2
Disposition                   0
KTAS_expert                   0
Error_group                   0
Length of stay_min            0
KTAS duration_min             0
mistriage                     0
dtype: int64

In [ ]:
cols = ['SBP', 'DBP', 'HR', 'RR', 'BT', 'NRS_pain', 'Saturation']

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  711 non-null    float64
 10  SBP                       1242 non-null   float64
 11  DBP                       1238 non-null   float64
 12  HR                        1247 non-null   float64
 13  RR                        1245 non-null   float64
 14  BT                        1249 non-null   float64
 15  Saturation                570 non-null    float64
 16  KTAS_RN                   1267 non-null   int64
 17  Diagnosis in ED           1265 non-null   object
 18  Disposition               1267 non-null   int64
 19  KTAS_expert               1267 non-null   int64
 20  Error_group               1267 non-null   int64
 21  Length of stay_min        1267 non-null   int64
 22  KTAS duration_min         1267 non-null   float64
 23  mistriage                 1267 non-null   int64
dtypes: float64(8), int64(14), object(2)
memory usage: 237.7+ KB

In [ ]:
df['target'] = df['KTAS_expert'].apply(lambda x: 1 if x in [1,2,3] else 0)

In [ ]:
print(df['target'].value_counts())

target
1    733
0    534
Name: count, dtype: int64

In [ ]:
print(df['mistriage'].value_counts())

mistriage
0    1081
2     131
1      55
Name: count, dtype: int64

In [ ]:
df['Saturation_missing'] = df['Saturation'].isnull().astype(int)
df['Saturation'].fillna(df['Saturation'].median(), inplace=True)

/tmp/ipykernel_4006/2396875985.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Saturation'].fillna(df['Saturation'].median(), inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  711 non-null    float64
 10  SBP                       1242 non-null   float64
 11  DBP                       1238 non-null   float64
 12  HR                        1247 non-null   float64
 13  RR                        1245 non-null   float64
 14  BT                        1249 non-null   float64
 15  Saturation                1267 non-null   float64
 16  KTAS_RN                   1267 non-null   int64
 17  Diagnosis in ED           1265 non-null   object
 18  Disposition               1267 non-null   int64
 19  KTAS_expert               1267 non-null   int64
 20  Error_group               1267 non-null   int64
 21  Length of stay_min        1267 non-null   int64
 22  KTAS duration_min         1267 non-null   float64
 23  mistriage                 1267 non-null   int64
 24  target                    1267 non-null   int64
 25  Saturation_missing        1267 non-null   int64
dtypes: float64(8), int64(16), object(2)
memory usage: 257.5+ KB

In [ ]:
drop_cols = [
    'KTAS_RN',
    'KTAS_expert',
    'Error_group',
    'Disposition',
    'Diagnosis in ED',
    'Length of stay_min'
]

df = df.drop(columns=drop_cols)

In [ ]:
df['Shock_Index'] = df['HR'] / df['SBP']
df['Pulse_Pressure'] = df['SBP'] - df['DBP']

In [ ]:
df['Age_group'] = pd.cut(df['Age'],
                        bins=[0,18,40,65,120],
                        labels=[0,1,2,3])

In [ ]:
categorical = ['Sex','Arrival mode','Injury','Mental','Pain','Age_group']
numerical = ['Age','Patients number per hour','SBP','DBP','HR','RR','BT',
             'NRS_pain','Saturation','Shock_Index','Pulse_Pressure']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  711 non-null    float64
 10  SBP                       1242 non-null   float64
 11  DBP                       1238 non-null   float64
 12  HR                        1247 non-null   float64
 13  RR                        1245 non-null   float64
 14  BT                        1249 non-null   float64
 15  Saturation                1267 non-null   float64
 16  KTAS duration_min         1267 non-null   float64
 17  mistriage                 1267 non-null   int64
 18  target                    1267 non-null   int64
 19  Saturation_missing        1267 non-null   int64
 20  Shock_Index               1242 non-null   float64
 21  Pulse_Pressure            1238 non-null   float64
 22  Age_group                 1267 non-null   category
dtypes: category(1), float64(10), int64(11), object(1)
memory usage: 219.3+ KB

In [ ]:
df.head()

,Group,Sex,Age,Patients number per hour,Arrival mode,Injury,Chief_complain,Mental,Pain,NRS_pain,...,RR,BT,Saturation,KTAS duration_min,mistriage,target,Saturation_missing,Shock_Index,Pulse_Pressure,Age_group
0,2,2,71,3,3,2,right ocular pain,1,1,2.0,...,18.0,36.6,100.0,5.00,1,0,0,0.525000,60.0,3
1,1,1,56,12,3,2,right forearm burn,1,1,2.0,...,20.0,36.5,98.0,3.95,1,0,1,0.437956,62.0,2
2,2,1,68,8,2,2,"arm pain, Lt",1,1,2.0,...,20.0,36.6,98.0,1.00,1,0,0,0.784615,50.0,3
3,1,2,71,8,1,1,ascites tapping,1,1,3.0,...,20.0,36.5,98.0,9.83,1,0,1,0.633094,45.0,3
4,1,2,58,4,3,1,"distension, abd",1,1,3.0,...,18.0,36.5,98.0,6.60,1,0,1,1.021978,24.0,2

In [ ]:
print(df['Mental'].value_counts())

Mental
1    1187
2      39
3      28
4      13
Name: count, dtype: int64

In [ ]:
df['mistriage_risk'] = df['mistriage'].apply(lambda x: 0 if x == 0 else 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  711 non-null    float64
 10  SBP                       1242 non-null   float64
 11  DBP                       1238 non-null   float64
 12  HR                        1247 non-null   float64
 13  RR                        1245 non-null   float64
 14  BT                        1249 non-null   float64
 15  Saturation                1267 non-null   float64
 16  KTAS duration_min         1267 non-null   float64
 17  mistriage                 1267 non-null   int64
 18  target                    1267 non-null   int64
 19  Saturation_missing        1267 non-null   int64
 20  Shock_Index               1242 non-null   float64
 21  Pulse_Pressure            1238 non-null   float64
 22  Age_group                 1267 non-null   category
 23  mistriage_risk            1267 non-null   int64
dtypes: category(1), float64(10), int64(12), object(1)
memory usage: 229.2+ KB

In [ ]:
print(df.columns)

Index(['Group', 'Sex', 'Age', 'Patients number per hour', 'Arrival mode',
       'Injury', 'Chief_complain', 'Mental', 'Pain', 'NRS_pain', 'SBP', 'DBP',
       'HR', 'RR', 'BT', 'Saturation', 'KTAS duration_min', 'mistriage',
       'target', 'Saturation_missing', 'Shock_Index', 'Pulse_Pressure',
       'Age_group', 'mistriage_risk'],
      dtype='object')

In [ ]:
df.drop(columns=['mistriage'], inplace=True, errors='ignore')

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['target', 'mistriage_risk'])
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
X_risk = df.drop(columns=['target', 'mistriage_risk'])
y_risk = df['mistriage_risk']

Xr_train, Xr_test, yr_train, yr_test = train_test_split(
    X_risk, y_risk, test_size=0.2, random_state=42, stratify=y_risk
)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [ ]:
categorical = [
    'Sex','Arrival mode','Injury','Mental','Pain','Age_group','Group'
]

numerical = [
    'Age','Patients number per hour',
    'SBP','DBP','HR','RR','BT',
    'NRS_pain','Saturation',
    'Shock_Index','Pulse_Pressure',
    'KTAS duration_min'
]

In [ ]:
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline([
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', num_pipeline, numerical),
    ('cat', cat_pipeline, categorical)
])

In [ ]:
!pip install xgboost --quiet

In [ ]:
import xgboost as xgb
urgency_model = Pipeline([
    ('prep', preprocessor),
    ('clf', xgb.XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=2,  # adjust for class imbalance
        random_state=42,
        use_label_encoder=False,
        eval_metric='logloss'
    ))
])

urgency_model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:36:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age',
                                                   'Patients number per hour',
                                                   'SBP', 'DBP', 'HR', 'RR',
                                                   'BT', 'NRS_pain',
                                                   'Saturation', 'Shock_Index',
                                                   'Pulse_Pressure',
                                                   'KTAS duration_min']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [ ]:
risk_model = Pipeline([
    ('prep', preprocessor),
    ('clf', xgb.XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=3,  # for rare class
        random_state=42,
        use_label_encoder=False,
        eval_metric='logloss'
    ))
])

risk_model.fit(Xr_train, yr_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:36:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age',
                                                   'Patients number per hour',
                                                   'SBP', 'DBP', 'HR', 'RR',
                                                   'BT', 'NRS_pain',
                                                   'Saturation', 'Shock_Index',
                                                   'Pulse_Pressure',
                                                   'KTAS duration_min']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [ ]:
from sklearn.metrics import classification_report

# Urgency
y_pred = urgency_model.predict(X_test)
print("Urgency Model:")
print(classification_report(y_test, y_pred))

# Risk
y_pred_risk = risk_model.predict(Xr_test)
print("Mistriage Risk Model:")
print(classification_report(yr_test, y_pred_risk))

Urgency Model:
              precision    recall  f1-score   support

           0       0.68      0.64      0.66       107
           1       0.75      0.78      0.77       147

    accuracy                           0.72       254
   macro avg       0.72      0.71      0.72       254
weighted avg       0.72      0.72      0.72       254

Mistriage Risk Model:
              precision    recall  f1-score   support

           0       0.86      0.95      0.91       217
           1       0.29      0.11      0.16        37

    accuracy                           0.83       254
   macro avg       0.57      0.53      0.53       254
weighted avg       0.78      0.83      0.80       254

In [ ]:
!pip install imbalanced-learn --quiet

In [ ]:
import joblib

joblib.dump(urgency_model, 'urgency_model.pkl')

['urgency_model.pkl']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

joblib.dump(urgency_model, '/content/drive/MyDrive/urgency_model.pkl')

Mounted at /content/drive

['/content/drive/MyDrive/urgency_model.pkl']

In [ ]:
df.isnull().sum()

Group                         0
Sex                           0
Age                           0
Patients number per hour      0
Arrival mode                  0
Injury                        0
Chief_complain                0
Mental                        0
Pain                          0
NRS_pain                    556
SBP                          25
DBP                          29
HR                           20
RR                           22
BT                           18
Saturation                    0
KTAS duration_min             0
target                        0
Saturation_missing            0
Shock_Index                  25
Pulse_Pressure               29
Age_group                     0
mistriage_risk                0
dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
Xr_train.head()

,Group,Sex,Age,Patients number per hour,Arrival mode,Injury,Chief_complain,Mental,Pain,NRS_pain,...,DBP,HR,RR,BT,Saturation,KTAS duration_min,Saturation_missing,Shock_Index,Pulse_Pressure,Age_group
153,2,2,65,7,2,2,mental change,3,0,NaN,...,NaN,100.0,20.0,36.0,94.0,2.00,0,1.428571,NaN,2
350,1,2,55,15,2,1,pain on Knee,2,1,3.0,...,69.0,101.0,20.0,36.5,98.0,12.48,1,0.909910,42.0,2
898,2,1,35,8,2,1,Vaginal Bleeding,1,0,NaN,...,60.0,102.0,20.0,36.5,99.0,1.00,0,1.020000,40.0,1
599,1,2,36,3,3,1,abd pain,1,1,5.0,...,86.0,79.0,18.0,36.8,98.0,2.72,1,0.585185,49.0,1
648,1,1,68,10,3,1,abd pain,1,1,5.0,...,79.0,60.0,20.0,36.6,98.0,5.22,1,0.402685,70.0,3

In [ ]:
Xr_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1013 entries, 153 to 843
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1013 non-null   int64
 1   Sex                       1013 non-null   int64
 2   Age                       1013 non-null   int64
 3   Patients number per hour  1013 non-null   int64
 4   Arrival mode              1013 non-null   int64
 5   Injury                    1013 non-null   int64
 6   Chief_complain            1013 non-null   object
 7   Mental                    1013 non-null   int64
 8   Pain                      1013 non-null   int64
 9   NRS_pain                  582 non-null    float64
 10  SBP                       992 non-null    float64
 11  DBP                       988 non-null    float64
 12  HR                        997 non-null    float64
 13  RR                        994 non-null    float64
 14  BT                        998 non-null    float64
 15  Saturation                1013 non-null   float64
 16  KTAS duration_min         1013 non-null   float64
 17  Saturation_missing        1013 non-null   int64
 18  Shock_Index               992 non-null    float64
 19  Pulse_Pressure            988 non-null    float64
 20  Age_group                 1013 non-null   category
dtypes: category(1), float64(10), int64(9), object(1)
memory usage: 167.4+ KB

In [ ]:
df = df.drop(columns=['Chief_complain'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Mental                    1267 non-null   int64
 7   Pain                      1267 non-null   int64
 8   NRS_pain                  711 non-null    float64
 9   SBP                       1242 non-null   float64
 10  DBP                       1238 non-null   float64
 11  HR                        1247 non-null   float64
 12  RR                        1245 non-null   float64
 13  BT                        1249 non-null   float64
 14  Saturation                1267 non-null   float64
 15  KTAS duration_min         1267 non-null   float64
 16  target                    1267 non-null   int64
 17  Saturation_missing        1267 non-null   int64
 18  Shock_Index               1242 non-null   float64
 19  Pulse_Pressure            1238 non-null   float64
 20  Age_group                 1267 non-null   category
 21  mistriage_risk            1267 non-null   int64
dtypes: category(1), float64(10), int64(11)
memory usage: 209.4 KB

In [ ]:
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline([
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', num_pipeline, numerical),
    ('cat', cat_pipeline, categorical)
])

In [ ]:
import xgboost as xgb

risk_model_1 = Pipeline([
    ('prep', preprocessor),   # handles NaN + encoding
    ('smote', SMOTE(random_state=42)),  # applied AFTER preprocessing
    ('clf', xgb.XGBClassifier(
        n_estimators=400,
        max_depth=6,
        learning_rate=0.03,
        subsample=0.9,
        colsample_bytree=0.9,
        scale_pos_weight=6,
        random_state=42,
        eval_metric='logloss'
    ))
])

In [ ]:
risk_model.fit(Xr_train, yr_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age',
                                                   'Patients number per hour',
                                                   'SBP', 'DBP', 'HR', 'RR',
                                                   'BT', 'NRS_pain',
                                                   'Saturation', 'Shock_Index',
                                                   'Pulse_Pressure',
                                                   'KTAS duration_min']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Predict on the test set
yr_pred = risk_model.predict(Xr_test)

# Accuracy
accuracy = accuracy_score(yr_test, yr_pred)
print(f"Accuracy: {accuracy:.4f}")

# Confusion Matrix
cm = confusion_matrix(yr_test, yr_pred)
print("Confusion Matrix:")
print(cm)

# Detailed Classification Report
report = classification_report(yr_test, yr_pred, target_names=["Low Risk (0)", "High Risk (1)"])
print("Classification Report for Mistriage Risk Model:")
print(report)

Accuracy: 0.8307
Confusion Matrix:
[[207  10]
 [ 33   4]]
Classification Report for Mistriage Risk Model:
               precision    recall  f1-score   support

 Low Risk (0)       0.86      0.95      0.91       217
High Risk (1)       0.29      0.11      0.16        37

     accuracy                           0.83       254
    macro avg       0.57      0.53      0.53       254
 weighted avg       0.78      0.83      0.80       254

In [ ]:
import joblib

# Save Urgency Model
joblib.dump(urgency_model, '/content/urgency_model_xgb.pkl')

# Save Risk Model
joblib.dump(risk_model, '/content/mistriage_risk_model_rf.pkl')

print("Models saved successfully!")

Models saved successfully!

In [ ]:
import os

print(os.listdir('/content'))

['.config', 'urgency_model_xgb.pkl', 'drive', 'urgency_model.pkl', 'mistriage_risk_model_rf.pkl', 'sample_data']

In [ ]:
from google.colab import files
files.download('/content/urgency_model_xgb.pkl')
files.download('/content/mistriage_risk_model_rf.pkl')

In [ ]:
# Separate X and y properly BEFORE any preprocessing
X_risk = df.drop(columns=['target', 'mistriage_risk'])
y_risk = df['mistriage_risk']

# Train-test split with stratification to preserve class distribution
from sklearn.model_selection import train_test_split

Xr_train, Xr_test, yr_train, yr_test = train_test_split(
    X_risk, y_risk, test_size=0.2, random_state=42, stratify=y_risk
)

print("Train size:", Xr_train.shape, "Test size:", Xr_test.shape)

Train size: (1013, 20) Test size: (254, 20)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

# Identify numeric and categorical columns
numeric_features = Xr_train.select_dtypes(include=['int64','float64']).columns.tolist()
categorical_features = Xr_train.select_dtypes(include=['object','category']).columns.tolist()

# Imputer for numeric, median strategy
numeric_transformer = SimpleImputer(strategy='median')

# Encoder for categorical
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

In [ ]:
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier

# Compute class weight
import numpy as np
n_low = sum(yr_train == 0)
n_high = sum(yr_train == 1)
scale_pos_weight = n_low / n_high
print("scale_pos_weight for high-risk class:", scale_pos_weight)

# Build pipeline
risk_model = Pipeline([
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)),
    ('classifier', XGBClassifier(
        n_estimators=200,
        learning_rate=0.1,
        max_depth=5,
        scale_pos_weight=scale_pos_weight,
        use_label_encoder=False,
        eval_metric='logloss',
        random_state=42
    ))
])

scale_pos_weight for high-risk class: 5.798657718120805

In [ ]:
risk_model.fit(Xr_train, yr_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  SimpleImputer(strategy='median'),
                                                  ['Group', 'Sex', 'Age',
                                                   'Patients number per hour',
                                                   'Arrival mode', 'Injury',
                                                   'Mental', 'Pain', 'NRS_pain',
                                                   'SBP', 'DBP', 'HR', 'RR',
                                                   'BT', 'Saturation',
                                                   'KTAS duration_min',
                                                   'Saturation_missing',
                                                   'Shock_Index',
                                                   'Pulse_Pressure']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='i...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=200, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Predictions
yr_pred = risk_model.predict(Xr_test)
yr_proba = risk_model.predict_proba(Xr_test)[:,1]

# Accuracy
print(f"Accuracy: {accuracy_score(yr_test, yr_pred):.4f}")

# Confusion matrix
print("Confusion Matrix:\n", confusion_matrix(yr_test, yr_pred))

# Classification report
print("Classification Report:")
print(classification_report(yr_test, yr_pred, target_names=["Low Risk (0)", "High Risk (1)"]))

Accuracy: 0.7953
Confusion Matrix:
 [[193  24]
 [ 28   9]]
Classification Report:
               precision    recall  f1-score   support

 Low Risk (0)       0.87      0.89      0.88       217
High Risk (1)       0.27      0.24      0.26        37

     accuracy                           0.80       254
    macro avg       0.57      0.57      0.57       254
 weighted avg       0.79      0.80      0.79       254

In [ ]:
from sklearn.model_selection import train_test_split

# Remove y variables from features to avoid leakage
X_risk = df.drop(columns=['target', 'mistriage_risk'])
y_risk = df['mistriage_risk']

# Stratified train-test split
Xr_train, Xr_test, yr_train, yr_test = train_test_split(
    X_risk, y_risk, test_size=0.2, random_state=42, stratify=y_risk
)

print("Train size:", Xr_train.shape, "Test size:", Xr_test.shape)

Train size: (1013, 20) Test size: (254, 20)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

# Identify numeric and categorical features
numeric_features = Xr_train.select_dtypes(include=['int64','float64']).columns.tolist()
categorical_features = Xr_train.select_dtypes(include=['object','category']).columns.tolist()

# Numeric imputer
numeric_transformer = SimpleImputer(strategy='median')

# Categorical encoder
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

# Column transformer
preprocessor = ColumnTransformer([
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

In [ ]:
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier

# Compute class weight
n_low = sum(yr_train == 0)
n_high = sum(yr_train == 1)
class_weight = {0:1, 1:n_low/n_high}
print("Class weight for high-risk:", class_weight)

# Pipeline
risk_rf_model = Pipeline([
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)),
    ('classifier', RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        random_state=42,
        class_weight=class_weight
    ))
])

Class weight for high-risk: {0: 1, 1: 5.798657718120805}

In [ ]:
risk_rf_model.fit(Xr_train, yr_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  SimpleImputer(strategy='median'),
                                                  ['Group', 'Sex', 'Age',
                                                   'Patients number per hour',
                                                   'Arrival mode', 'Injury',
                                                   'Mental', 'Pain', 'NRS_pain',
                                                   'SBP', 'DBP', 'HR', 'RR',
                                                   'BT', 'Saturation',
                                                   'KTAS duration_min',
                                                   'Saturation_missing',
                                                   'Shock_Index',
                                                   'Pulse_Pressure']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Age_group'])])),
                ('smote', SMOTE(random_state=42)),
                ('classifier',
                 RandomForestClassifier(class_weight={0: 1,
                                                      1: 5.798657718120805},
                                        max_depth=10, n_estimators=200,
                                        random_state=42))])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Predictions
yr_pred = risk_rf_model.predict(Xr_test)
yr_proba = risk_rf_model.predict_proba(Xr_test)[:,1]

# Accuracy
print(f"Accuracy: {accuracy_score(yr_test, yr_pred):.4f}")

# Confusion matrix
print("Confusion Matrix:\n", confusion_matrix(yr_test, yr_pred))

# Classification report
print("Classification Report:")
print(classification_report(yr_test, yr_pred, target_names=["Low Risk (0)", "High Risk (1)"]))

Accuracy: 0.6457
Confusion Matrix:
 [[151  66]
 [ 24  13]]
Classification Report:
               precision    recall  f1-score   support

 Low Risk (0)       0.86      0.70      0.77       217
High Risk (1)       0.16      0.35      0.22        37

     accuracy                           0.65       254
    macro avg       0.51      0.52      0.50       254
 weighted avg       0.76      0.65      0.69       254