<a href="https://colab.research.google.com/github/YM1587/care-me/blob/main/patient_triage_management.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ilkeryildiz/emergency-service-triage-application")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/ilkeryildiz/emergency-service-triage-application/2.archive...

100%|██████████| 36.2k/36.2k [00:00<00:00, 31.6MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/ilkeryildiz/emergency-service-triage-application/versions/2

In [2]:
import os
import pandas as pd

# List contents of the downloaded directory
print("Files in dataset directory:")
for dirname, _, filenames in os.walk(path):
    for filename in filenames:
        print(os.path.join(dirname, filename))

Files in dataset directory:
/root/.cache/kagglehub/datasets/ilkeryildiz/emergency-service-triage-application/versions/2/data.csv

In [3]:
data_file_path = os.path.join(path, 'data.csv')
df = pd.read_csv(data_file_path, encoding='latin1', sep=';', decimal=',')

display(df.head())

,Group,Sex,Age,Patients number per hour,Arrival mode,Injury,Chief_complain,Mental,Pain,NRS_pain,...,BT,Saturation,KTAS_RN,Diagnosis in ED,Disposition,KTAS_expert,Error_group,Length of stay_min,KTAS duration_min,mistriage
0,2,2,71,3,3,2,right ocular pain,1,1,2,...,36.6,100,2,Corneal abrasion,1,4,2,86,5.00,1
1,1,1,56,12,3,2,right forearm burn,1,1,2,...,36.5,NaN,4,"Burn of hand, firts degree dorsum",1,5,4,64,3.95,1
2,2,1,68,8,2,2,"arm pain, Lt",1,1,2,...,36.6,98,4,"Fracture of surgical neck of humerus, closed",2,5,4,862,1.00,1
3,1,2,71,8,1,1,ascites tapping,1,1,3,...,36.5,NaN,4,Alcoholic liver cirrhosis with ascites,1,5,6,108,9.83,1
4,1,2,58,4,3,1,"distension, abd",1,1,3,...,36.5,NaN,4,Ascites,1,5,8,109,6.60,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  1267 non-null   object
 10  SBP                       1267 non-null   object
 11  DBP                       1267 non-null   object
 12  HR                        1267 non-null   object
 13  RR                        1267 non-null   object
 14  BT                        1267 non-null   object
 15  Saturation                579 non-null    object
 16  KTAS_RN                   1267 non-null   int64
 17  Diagnosis in ED           1265 non-null   object
 18  Disposition               1267 non-null   int64
 19  KTAS_expert               1267 non-null   int64
 20  Error_group               1267 non-null   int64
 21  Length of stay_min        1267 non-null   int64
 22  KTAS duration_min         1267 non-null   float64
 23  mistriage                 1267 non-null   int64
dtypes: float64(1), int64(14), object(9)
memory usage: 237.7+ KB

In [5]:
df.isnull().sum()

Group                         0
Sex                           0
Age                           0
Patients number per hour      0
Arrival mode                  0
Injury                        0
Chief_complain                0
Mental                        0
Pain                          0
NRS_pain                      0
SBP                           0
DBP                           0
HR                            0
RR                            0
BT                            0
Saturation                  688
KTAS_RN                       0
Diagnosis in ED               2
Disposition                   0
KTAS_expert                   0
Error_group                   0
Length of stay_min            0
KTAS duration_min             0
mistriage                     0
dtype: int64

In [8]:
cols = ['SBP', 'DBP', 'HR', 'RR', 'BT', 'NRS_pain', 'Saturation']

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  711 non-null    float64
 10  SBP                       1242 non-null   float64
 11  DBP                       1238 non-null   float64
 12  HR                        1247 non-null   float64
 13  RR                        1245 non-null   float64
 14  BT                        1249 non-null   float64
 15  Saturation                570 non-null    float64
 16  KTAS_RN                   1267 non-null   int64
 17  Diagnosis in ED           1265 non-null   object
 18  Disposition               1267 non-null   int64
 19  KTAS_expert               1267 non-null   int64
 20  Error_group               1267 non-null   int64
 21  Length of stay_min        1267 non-null   int64
 22  KTAS duration_min         1267 non-null   float64
 23  mistriage                 1267 non-null   int64
dtypes: float64(8), int64(14), object(2)
memory usage: 237.7+ KB

In [11]:
df['target'] = df['KTAS_expert'].apply(lambda x: 1 if x in [1,2,3] else 0)

In [12]:
print(df['target'].value_counts())

target
1    733
0    534
Name: count, dtype: int64

In [13]:
print(df['mistriage'].value_counts())

mistriage
0    1081
2     131
1      55
Name: count, dtype: int64

In [14]:
df['Saturation_missing'] = df['Saturation'].isnull().astype(int)
df['Saturation'].fillna(df['Saturation'].median(), inplace=True)

/tmp/ipykernel_4853/2396875985.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Saturation'].fillna(df['Saturation'].median(), inplace=True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  711 non-null    float64
 10  SBP                       1242 non-null   float64
 11  DBP                       1238 non-null   float64
 12  HR                        1247 non-null   float64
 13  RR                        1245 non-null   float64
 14  BT                        1249 non-null   float64
 15  Saturation                1267 non-null   float64
 16  KTAS_RN                   1267 non-null   int64
 17  Diagnosis in ED           1265 non-null   object
 18  Disposition               1267 non-null   int64
 19  KTAS_expert               1267 non-null   int64
 20  Error_group               1267 non-null   int64
 21  Length of stay_min        1267 non-null   int64
 22  KTAS duration_min         1267 non-null   float64
 23  mistriage                 1267 non-null   int64
 24  target                    1267 non-null   int64
 25  Saturation_missing        1267 non-null   int64
dtypes: float64(8), int64(16), object(2)
memory usage: 257.5+ KB

In [16]:
drop_cols = [
    'KTAS_RN',
    'KTAS_expert',
    'Error_group',
    'Disposition',
    'Diagnosis in ED',
    'Length of stay_min'
]

df = df.drop(columns=drop_cols)

In [17]:
df['Shock_Index'] = df['HR'] / df['SBP']
df['Pulse_Pressure'] = df['SBP'] - df['DBP']

In [18]:
df['Age_group'] = pd.cut(df['Age'],
                        bins=[0,18,40,65,120],
                        labels=[0,1,2,3])

In [19]:
categorical = ['Sex','Arrival mode','Injury','Mental','Pain','Age_group']
numerical = ['Age','Patients number per hour','SBP','DBP','HR','RR','BT',
             'NRS_pain','Saturation','Shock_Index','Pulse_Pressure']

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  711 non-null    float64
 10  SBP                       1242 non-null   float64
 11  DBP                       1238 non-null   float64
 12  HR                        1247 non-null   float64
 13  RR                        1245 non-null   float64
 14  BT                        1249 non-null   float64
 15  Saturation                1267 non-null   float64
 16  KTAS duration_min         1267 non-null   float64
 17  mistriage                 1267 non-null   int64
 18  target                    1267 non-null   int64
 19  Saturation_missing        1267 non-null   int64
 20  Shock_Index               1242 non-null   float64
 21  Pulse_Pressure            1238 non-null   float64
 22  Age_group                 1267 non-null   category
dtypes: category(1), float64(10), int64(11), object(1)
memory usage: 219.3+ KB

In [21]:
df.head()

,Group,Sex,Age,Patients number per hour,Arrival mode,Injury,Chief_complain,Mental,Pain,NRS_pain,...,RR,BT,Saturation,KTAS duration_min,mistriage,target,Saturation_missing,Shock_Index,Pulse_Pressure,Age_group
0,2,2,71,3,3,2,right ocular pain,1,1,2.0,...,18.0,36.6,100.0,5.00,1,0,0,0.525000,60.0,3
1,1,1,56,12,3,2,right forearm burn,1,1,2.0,...,20.0,36.5,98.0,3.95,1,0,1,0.437956,62.0,2
2,2,1,68,8,2,2,"arm pain, Lt",1,1,2.0,...,20.0,36.6,98.0,1.00,1,0,0,0.784615,50.0,3
3,1,2,71,8,1,1,ascites tapping,1,1,3.0,...,20.0,36.5,98.0,9.83,1,0,1,0.633094,45.0,3
4,1,2,58,4,3,1,"distension, abd",1,1,3.0,...,18.0,36.5,98.0,6.60,1,0,1,1.021978,24.0,2

In [23]:
print(df['Mental'].value_counts())

Mental
1    1187
2      39
3      28
4      13
Name: count, dtype: int64

In [27]:
df['mistriage_risk'] = df['mistriage'].apply(lambda x: 0 if x == 0 else 1)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  711 non-null    float64
 10  SBP                       1242 non-null   float64
 11  DBP                       1238 non-null   float64
 12  HR                        1247 non-null   float64
 13  RR                        1245 non-null   float64
 14  BT                        1249 non-null   float64
 15  Saturation                1267 non-null   float64
 16  KTAS duration_min         1267 non-null   float64
 17  mistriage                 1267 non-null   int64
 18  target                    1267 non-null   int64
 19  Saturation_missing        1267 non-null   int64
 20  Shock_Index               1242 non-null   float64
 21  Pulse_Pressure            1238 non-null   float64
 22  Age_group                 1267 non-null   category
 23  mistriage_risk            1267 non-null   int64
dtypes: category(1), float64(10), int64(12), object(1)
memory usage: 229.2+ KB

In [38]:
print(df.columns)

Index(['Group', 'Sex', 'Age', 'Patients number per hour', 'Arrival mode',
       'Injury', 'Chief_complain', 'Mental', 'Pain', 'NRS_pain', 'SBP', 'DBP',
       'HR', 'RR', 'BT', 'Saturation', 'KTAS duration_min', 'mistriage',
       'target', 'Saturation_missing', 'Shock_Index', 'Pulse_Pressure',
       'Age_group', 'mistriage_risk'],
      dtype='object')

In [39]:
df.drop(columns=['mistriage'], inplace=True, errors='ignore')

In [40]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['target', 'mistriage_risk'])
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [41]:
X_risk = df.drop(columns=['target', 'mistriage_risk'])
y_risk = df['mistriage_risk']

Xr_train, Xr_test, yr_train, yr_test = train_test_split(
    X_risk, y_risk, test_size=0.2, random_state=42, stratify=y_risk
)

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [43]:
categorical = [
    'Sex','Arrival mode','Injury','Mental','Pain','Age_group','Group'
]

numerical = [
    'Age','Patients number per hour',
    'SBP','DBP','HR','RR','BT',
    'NRS_pain','Saturation',
    'Shock_Index','Pulse_Pressure',
    'KTAS duration_min'
]

In [44]:
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline([
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', num_pipeline, numerical),
    ('cat', cat_pipeline, categorical)
])

In [46]:
!pip install xgboost --quiet

In [47]:
import xgboost as xgb
urgency_model = Pipeline([
    ('prep', preprocessor),
    ('clf', xgb.XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=2,  # adjust for class imbalance
        random_state=42,
        use_label_encoder=False,
        eval_metric='logloss'
    ))
])

urgency_model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [17:05:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age',
                                                   'Patients number per hour',
                                                   'SBP', 'DBP', 'HR', 'RR',
                                                   'BT', 'NRS_pain',
                                                   'Saturation', 'Shock_Index',
                                                   'Pulse_Pressure',
                                                   'KTAS duration_min']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [48]:
risk_model = Pipeline([
    ('prep', preprocessor),
    ('clf', xgb.XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=3,  # for rare class
        random_state=42,
        use_label_encoder=False,
        eval_metric='logloss'
    ))
])

risk_model.fit(Xr_train, yr_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [17:06:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age',
                                                   'Patients number per hour',
                                                   'SBP', 'DBP', 'HR', 'RR',
                                                   'BT', 'NRS_pain',
                                                   'Saturation', 'Shock_Index',
                                                   'Pulse_Pressure',
                                                   'KTAS duration_min']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [49]:
from sklearn.metrics import classification_report

# Urgency
y_pred = urgency_model.predict(X_test)
print("Urgency Model:")
print(classification_report(y_test, y_pred))

# Risk
y_pred_risk = risk_model.predict(Xr_test)
print("Mistriage Risk Model:")
print(classification_report(yr_test, y_pred_risk))

Urgency Model:
              precision    recall  f1-score   support

           0       0.68      0.64      0.66       107
           1       0.75      0.78      0.77       147

    accuracy                           0.72       254
   macro avg       0.72      0.71      0.72       254
weighted avg       0.72      0.72      0.72       254

Mistriage Risk Model:
              precision    recall  f1-score   support

           0       0.86      0.95      0.91       217
           1       0.29      0.11      0.16        37

    accuracy                           0.83       254
   macro avg       0.57      0.53      0.53       254
weighted avg       0.78      0.83      0.80       254